### ISSUE TITLE
How to run these JFileman??

### ISSUE THREAD

**Issue by manucr619** [developerSid/JFileMan#1]
I downloaded and don't know how to run these code bro.

**Comment by developerSid** [comment]
Honestly it probably doesn't run.  It was something I was playing with several years ago as a replacement for an PHP based file manager we used internally at my job.  I never got time to work on it, and the need for it went away so it is just kind of hanging out basically dead.

**Comment by manucr619** [comment]
ok, thanks Sid. for your reply.
